In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

In [ ]:

df=pd.read_csv('FIFA2022.csv')

In [3]:
df

,Position,Team,Games Played,Win,Draw,Loss,Goals For,Goals Against,Goal Difference,Points
0,1,Argentina,7,6,0,1,15,8,7,18
1,2,France,7,5,0,2,16,8,8,15
2,3,Croatia,7,4,2,1,8,7,1,14
3,4,Morocco,7,4,1,2,6,5,1,13
4,5,England,5,3,1,1,13,4,9,10
5,6,Netherlands,5,3,1,1,10,4,6,10
6,7,Portugal,5,3,0,2,12,6,6,9
7,8,Brazil,5,3,0,2,8,3,5,9
8,9,Japan,4,2,0,2,5,4,1,6
9,10,Senegal,4,2,0,2,5,7,-2,6
10,11,Australia,4,2,0,2,4,6,-2,6
11,12,Switzerland,4,2,0,2,5,9,-4,6
12,13,USA,4,1,2,1,3,4,-1,5
13,14,Spain,4,1,1,2,9,3,6,4
14,15,Poland,4,1,1,2,3,5,-2,4
15,16,South Korea,4,1,1,2,5,8,-3,4
16,17,Germany,3,1,1,1,6,5,1,4
17,18,Ecuador,3,1,1,1,4,3,1,4
18,19,Cameroon,3,1,1,1,4,4,0,4
19,20,Uruguay,3,1,1,1,2,2,0,4
20,21,Tunisia,3,1,1,1,1,1,0,4
21,22,Mexico,3,1,1,1,2,3,-1,4
22,23,Belgium,3,1,1,1,1,2,-1,4
23,24,Ghana,3,1,0,2,5,7,-2,3
24,25,Saudi Arabia,3,1,0,2,3,5,-2,3
25,26,Iran,3,1,0,2,4,7,-3,3
26,27,Costa Rica,3,1,0,2,3,11,-8,3
27,28,Denmark,3,0,1,2,1,3,-2,1
28,29,Serbia,3,0,1,2,5,8,-3,1
29,30,Wales,3,0,1,2,1,6,-5,1
30,31,Canada,3,0,0,3,2,7,-5,0
31,32,Qatar,3,0,0,3,1,7,-6,0

In [4]:
label_encoder = LabelEncoder()

In [6]:
df['Team'] = label_encoder.fit_transform(df['Team'])

In [7]:
df

,Position,Team,Games Played,Win,Draw,Loss,Goals For,Goals Against,Goal Difference,Points
0,1,0,7,6,0,1,15,8,7,18
1,2,11,7,5,0,2,16,8,8,15
2,3,7,7,4,2,1,8,7,1,14
3,4,17,7,4,1,2,6,5,1,13
4,5,10,5,3,1,1,13,4,9,10
5,6,18,5,3,1,1,10,4,6,10
6,7,20,5,3,0,2,12,6,6,9
7,8,3,5,3,0,2,8,3,5,9
8,9,15,4,2,0,2,5,4,1,6
9,10,23,4,2,0,2,5,7,-2,6
10,11,1,4,2,0,2,4,6,-2,6
11,12,27,4,2,0,2,5,9,-4,6
12,13,29,4,1,2,1,3,4,-1,5
13,14,26,4,1,1,2,9,3,6,4
14,15,19,4,1,1,2,3,5,-2,4
15,16,25,4,1,1,2,5,8,-3,4
16,17,12,3,1,1,1,6,5,1,4
17,18,9,3,1,1,1,4,3,1,4
18,19,4,3,1,1,1,4,4,0,4
19,20,30,3,1,1,1,2,2,0,4
20,21,28,3,1,1,1,1,1,0,4
21,22,16,3,1,1,1,2,3,-1,4
22,23,2,3,1,1,1,1,2,-1,4
23,24,13,3,1,0,2,5,7,-2,3
24,25,22,3,1,0,2,3,5,-2,3
25,26,14,3,1,0,2,4,7,-3,3
26,27,6,3,1,0,2,3,11,-8,3
27,28,8,3,0,1,2,1,3,-2,1
28,29,24,3,0,1,2,5,8,-3,1
29,30,31,3,0,1,2,1,6,-5,1
30,31,5,3,0,0,3,2,7,-5,0
31,32,21,3,0,0,3,1,7,-6,0

In [9]:
X = df.drop('Points', axis=1)
y = df['Points']

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

In [12]:
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [13]:
y_pred=rf_classifier.predict(X_test)
y_pred

array([1, 4, 3, 4, 6, 6, 0], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("accuracy level   :",accuracy)

accuracy level   : 1.0

In [16]:
y_pred = rf_classifier.predict([[2,11,7,5,0,2,16,8,15]])

C:\Users\tulasi\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [17]:
y_pred

array([15], dtype=int64)